# modes.conf — configs dos 3 modos de desempenho
# Modificar requer reaplicar o modo: perfctl set <0|1|2>

# --- Standard ---
BALANCED_CPU0_MIN=
BALANCED_CPU0_MAX=
BALANCED_CPU3_MIN=
BALANCED_CPU3_MAX=
BALANCED_CPU7_MIN=
BALANCED_CPU7_MAX=
BALANCED_GPU_MIN=
BALANCED_GPU_MAX=
BALANCED_GPU_LOCK=0
BALANCED_DDR_MIN=
BALANCED_SCHED_ENERGY=1
BALANCED_SCHED_PELT_MULT=1
BALANCED_WALT_BOOST=0
BALANCED_RTG_BOOST=0
BALANCED_GPU_TRIP_AUTO=
BALANCED_CPU_TRIP_AUTO=
BALANCED_TOPAPP_CPUS=default
BALANCED_BG_CPUS=default
BALANCED_KEEPER=0

# --- Performance ---
PERF_CPU0_MIN=1228800
PERF_CPU0_MAX=2016000
PERF_CPU3_MIN=2054400
PERF_CPU3_MAX=2803200
PERF_CPU7_MIN=2476800
PERF_CPU7_MAX=3187200
PERF_GPU_MIN=401000000
PERF_GPU_MAX=1000000000
PERF_GPU_LOCK=0
PERF_DDR_MIN=4224000
PERF_SCHED_ENERGY=1
PERF_SCHED_PELT_MULT=1
PERF_WALT_BOOST=0
PERF_RTG_BOOST=0
PERF_GPU_TRIP_AUTO=105000
PERF_CPU_TRIP_AUTO=105000
PERF_TOPAPP_CPUS=default
PERF_BG_CPUS=default
PERF_KEEPER=1

# --- High Performance ---
HIGH_CPU0_MIN=2016000
HIGH_CPU0_MAX=2016000
HIGH_CPU3_MIN=499200
HIGH_CPU3_MAX=2803200
HIGH_CPU7_MIN=595200
HIGH_CPU7_MAX=3360000
HIGH_GPU_MIN=124800000
HIGH_GPU_MAX=1000000000
HIGH_GPU_LOCK=0
HIGH_DDR_MIN=4224000
HIGH_SCHED_ENERGY=1
HIGH_SCHED_PELT_MULT=4
HIGH_WALT_BOOST=1
HIGH_RTG_BOOST=3360000
HIGH_GPU_TRIP_AUTO=110000
HIGH_CPU_TRIP_AUTO=110000
HIGH_TOPAPP_CPUS=3-7
HIGH_BG_CPUS=0-2
HIGH_KEEPER=1
